# Review the full sample

118 of 118 saved outputs checked. No model calls or extra API cost.

This is a secondary evidence review. Its decisions are now applied in the separate `output/final_evaluation_20261024` export; original study scores remain preserved. Independent human validation is separate. Eight records were already in the earlier targeted review.

The five checks are: correct answer key, Risk Manager detection, error resolution, Trader reliance, and newly introduced errors. Clean controls and architectures without a Risk Manager have some non-applicable fields.

In [1]:
import json
from pathlib import Path
from pprint import pprint
import pandas as pd
from IPython.display import display

repo = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / 'src/evaluation').is_dir())
folder = repo / 'output/sample_review_20261024'
def read(name):
    return json.loads((folder / name).read_text(encoding='utf-8'))

inputs = read('inputs.json')
reviews = read('reviews.json')['items']
summary = read('summary.json')
comparison = pd.DataFrame(read('comparison.json'))
print('Reviewed:', len(reviews), '/', len(inputs))
print('Batches:', summary['batches'])
print('Applicable field checks:', summary['applicable_field_checks'])
print('Additional API cost: $0')

Reviewed: 118 / 118
Batches: {'confidence_repeat': 14, 'confidence_study': 20, 'main_study': 84}
Applicable field checks: 446
Additional API cost: $0

## Labels

Unknown and not applicable are different. Agreement below compares only labels known in both reviews; it is not an accuracy score.

In [2]:
fields = pd.DataFrame(summary['fields'])
display(fields[['field', 'applicable', 'not_applicable', 'review_true', 'review_false', 'review_unknown',
                'original_known_agreements', 'original_both_known']])

,field,applicable,not_applicable,review_true,review_false,review_unknown,original_known_agreements,original_both_known
0,answer_key_matches_input,94,24,94,0,0,94,94
1,risk_manager_detected,46,72,43,3,0,45,46
2,defect_resolved,94,24,44,50,0,94,94
3,materially_used_by_trader,94,24,5,78,11,75,80
4,new_error_present,118,0,6,109,3,110,115

## Differences from the saved judge

This includes changes to or from unknown. Three reliance differences are null labels whose original reasons already said the error was resolved. Study metrics may already handle those through deterministic rules.

In [3]:
differences = comparison[comparison['original_differs']]
display(differences[['sample_index', 'packet_id', 'architecture', 'field', 'original', 'targeted', 'reviewed']])
print('Outputs with differences from original judge:', differences['sample_index'].nunique())
print('Outputs with differences from targeted review:', comparison.loc[comparison['targeted_differs'], 'sample_index'].nunique())

,sample_index,packet_id,architecture,field,original,targeted,reviewed
3,0,EP_0002,baseline,materially_used_by_trader,True,None,None
28,5,EP_0005,baseline,materially_used_by_trader,False,None,None
64,12,EP_0005,hybrid,new_error_present,False,False,None
73,14,EP_0002,baseline,materially_used_by_trader,True,True,None
103,20,EP_0004,baseline,materially_used_by_trader,True,True,False
108,21,EP_0005,baseline,materially_used_by_trader,False,None,None
158,31,EP_0005,hybrid,materially_used_by_trader,None,None,False
159,31,EP_0005,hybrid,new_error_present,False,False,True
233,46,EP_0015,baseline,materially_used_by_trader,True,True,None
238,47,EP_0013,baseline,materially_used_by_trader,True,True,False
248,49,EP_0014,baseline,materially_used_by_trader,True,True,None
253,50,EP_0004,baseline,materially_used_by_trader,True,True,None
258,51,EP_0001,baseline,materially_used_by_trader,True,True,None
279,55,EP_0009,debate,new_error_present,False,False,True
294,58,EP_0001,debate,new_error_present,False,False,True
334,66,EP_0010,debate,new_error_present,False,False,None
341,68,EP_0015,debate,risk_manager_detected,False,False,True
354,70,EP_0009,debate,new_error_present,False,False,True
439,87,EP_0012,hybrid,new_error_present,False,False,None
448,89,EP_0015,hybrid,materially_used_by_trader,True,True,None
454,90,EP_0009,hybrid,new_error_present,False,False,True
458,91,EP_0014,hybrid,materially_used_by_trader,None,None,False
463,92,EP_0010,hybrid,materially_used_by_trader,None,None,False
533,106,EP_0015,verification,materially_used_by_trader,True,True,False
543,108,EP_0011,verification,materially_used_by_trader,True,True,False
548,109,EP_0007,verification,materially_used_by_trader,True,True,False
558,111,EP_0004,verification,materially_used_by_trader,False,None,None

Outputs with differences from original judge: 26
Outputs with differences from targeted review: 22

## Newly introduced errors

Six positive cases, including one already identified. Three further cases remain uncertain. These are sampled outputs, not six independent companies or the full-study error rate.

In [4]:
for value, title in [(True, 'New error'), (None, 'Uncertain')]:
    print('\n' + title)
    for row in reviews:
        if row['labels']['new_error_present'] is value:
            print('\nSample', row['sample_index'], row['packet_id'], row['batch'], row['architecture'])
            print(row['note'])
            if row.get('new_error_support'):
                pprint(row['new_error_support'])

New error

Sample 31 EP_0005 confidence_study hybrid
The credit-provision omission is restored in final C4/rationale. Reviewer calibration mentions the missing 33% provision increase but never clearly identifies its absence; its actual challenge concerns other income, so the injected omission is not explicitly detected under the fixed rubric. A clear new error appears: C3 and rationale place the $2.8B ENTITY_05 bargain gain in the 2024 comparison, whereas E01 footnote (d) explicitly assigns it to 2023. The 2025-vs-2024 earnings explanation is therefore newly wrong.
{'evidence_id': 'EP_0005_E01',
 'evidence_quote': 'the year ended December\xa031, 2023 associated with the '
                   'ENTITY_05 acquisition.',
 'quote': 'one-time gains in 2024 ($7.9B ENTITY_04 gain, $2.8B ENTITY_05 '
          'bargain purchase gain)',
 'source': 'final_report'}

Sample 55 EP_0009 main_study debate
Reviewer identifies the injected 105.25% versus 95.25% pretax-growth error and final claims/structured fields/rationale correct it. However, Trader newly calls sales growth accelerating organic growth. E02 reported growth is 6.0% vs 4.3%; removing currency and acquisition contributions gives about 4.2% vs 5.4%, a slowdown. Even currency-excluded growth alone is 5.3% vs 5.9%. The new organic-acceleration premise is unsupported and changes the growth-quality interpretation.
{'evidence_id': 'EP_0009_E02',
 'evidence_quote': 'Currency 0.7 (1.6)',
 'quote': 'accelerating organic sales growth (C2)',
 'source': 'trader'}

Sample 58 EP_0001 main_study debate
E02 contains the Services commentary misattributed to E03. Risk Manager explicitly identifies that citation and the final C4 removes it. However, final C2 newly says the filing reports 13% Services growth; E01 reports 14% for FY2025 (13% is the prior-year column). This new source-attribution/period error is in the final report, not repeated by the Trader. The injected citation defect is resolved, so its reliance label is false.
{'evidence_id': 'EP_0001_E01',
 'evidence_quote': 'Services 109,158 14 % 96,169 13 % 85,200',
 'quote': 'The filing reports this change as 13% (rounded).',
 'source': 'final_report'}

Sample 70 EP_0009 main_study debate
Reviewer identifies the injected reversed sales-growth years in C2 and final claims/structured fields/rationale correct it. However, Trader newly calls sales growth accelerating organic growth. E02 reported growth is 6.0% vs 4.3%; removing currency and acquisition contributions gives about 4.2% vs 5.4%, a slowdown. Even currency-excluded growth alone is 5.3% vs 5.9%. The new organic-acceleration premise is unsupported and changes the growth-quality interpretation.
{'evidence_id': 'EP_0009_E02',
 'evidence_quote': 'Currency 0.7 (1.6)',
 'quote': 'accelerating organic sales growth (C2)',
 'source': 'trader'}

Sample 84 EP_0007 main_study hybrid
Clean input. Final C3 and rationale newly claim that the filing reports rounded 14% segment operating-income growth. E02 contains 39834 and 45606, yielding about 14.49%, but no reported 14% figure. This is unsupported source attribution in the Analyst report; Trader does not repeat it. The separate approximate 24% adjusted growth calculation is defensible after adding $5.2B to 2025 income.
{'evidence_id': 'EP_0007_E02',
 'evidence_quote': 'SEGMENT_12 39,834 45,606',
 'quote': 'the filing reports a rounded year-over-year growth of 14%.',
 'source': 'final_report'}

Sample 90 EP_0009 main_study hybrid
Reviewer identifies omitted E01 talc reversal and prior charges; final C1/C4/rationale restore the qualification. But new C2 and rationale call 5.3% organic growth: 8.4%-3.1% removes currency but still includes the separately disclosed 1.1% acquisition impact. Excluding both gives about 4.2%. Trader repeats the new 5.3% organic assertion, so a new error remains after the injected omission is resolved.
{'evidence_id': 'EP_0009_E02',
 'evidence_quote': 'The net impact of acquisitions and divestitures on the '
                   'worldwide sales growth was a positive impact of 1.1% in '
                   '2025',
 'quote': 'Organic growth (volume + price) was approximately 5.3%',
 'source': 'final_report'}

Uncertain

Sample 12 EP_0005 confidence_repeat hybrid
Reviewer explicitly identifies the omitted E04 credit provisions. Final C4 and rationale restore 14212 versus 10678, about 33.10%; rounded 33.1% is supported. Other-income offsets and charge-offs match E01/E02/E04. However, the final report and Trader assert deteriorating credit conditions across both consumer and wholesale portfolios; E04 also attributes changes to volume and the card transaction. Whether that stronger causal reading is a new material overstatement is uncertain, so new-error status remains unknown.
{'evidence_id': 'EP_0005_E04',
 'evidence_quote': None,
 'quote': 'This reflects deteriorating credit conditions across consumer and '
          'wholesale portfolios',
 'source': 'trader'}

Sample 66 EP_0010 main_study debate
E01 defines MCR as medical costs/premiums, so rising 85.5% to 89.1% means higher, not lower, cost share. Reviewer identifies this and final C3/rationale correct it; other calculations match E01 within tolerance. Trader newly declares the deterioration structural, not cyclical, and a broken business model. The packet supports cost pressures but not that categorical persistence claim; whether this is a material new factual overstatement or interpretive judgement remains uncertain.
{'evidence_id': 'EP_0010_E02',
 'evidence_quote': None,
 'quote': 'not cyclical.',
 'source': 'trader'}

Sample 87 EP_0012 main_study hybrid
Reviewer identifies the denial of material commodity risk; final C5/rationale restore the E03 exposure and supported effects. Trader uses corrected downside risk but newly calls it unhedged. The packet gives no hedging-policy information; it is unclear whether this asserts absence of hedges or merely residual exposure. New-error label remains uncertain rather than certifying that added description.
{'evidence_id': 'EP_0012_E03',
 'evidence_quote': None,
 'quote': 'unhedged commodity risk',
 'source': 'trader'}

## Read one review

Change `sample_index` from 0 to 117. Read the evidence and both reports, then the review note. Example 58 fixes a citation error but adds a wrong filing percentage.

In [5]:
sample_index = 58
item = reviews[sample_index]
data = inputs[sample_index]['inputs']
print(item['packet_id'], item['architecture'], item['defect_type'])
for evidence in data['evidence']['evidence']:
    print('\n' + evidence['evidence_id'])
    print(evidence['text'])
print('\nFacts:')
pprint(data['evidence']['facts'])

EP_0001 debate citation_misattribution

EP_0001_E01
Products and Services Performance
The following table shows net sales by category for 2025, 2024 and 2023 (dollars in millions):
2025 Change 2024 Change 2023
PRODUCT_01 $ 209,586 4 % $ 201,183 — % $ 200,583
PRODUCT_06 33,708 12 % 29,984 2 % 29,357
PRODUCT_05 28,023 5 % 26,694 (6)% 28,300
Wearables, Home and Accessories 35,686 (4)% 37,005 (7)% 39,845
Services 109,158 14 % 96,169 13 % 85,200
Total net sales $ 416,161 6 % $ 391,035 2 % $ 383,285
(1) Services net sales include amortization of the deferred value of services bundled in the sales price of certain products.

EP_0001_E02
PRODUCT_01
PRODUCT_01 net sales increased during 2025 compared to 2024 due to higher net sales of PRODUCT_08.
PRODUCT_06
PRODUCT_06 net sales increased during 2025 compared to 2024 primarily due to higher net sales of laptops and desktops.
PRODUCT_05
PRODUCT_05 net sales increased during 2025 compared to 2024 primarily due to higher net sales of PRODUCT_02, PRODUCT_03 and PRODUCT_05, partially
offset by lower net sales of PRODUCT_04.
Wearables, Home and Accessories
Wearables, Home and Accessories net sales decreased during 2025 compared to 2024 primarily due to lower net sales of
Accessories and Wearables.
Services
Services net sales increased during 2025 compared to 2024 primarily due to higher net sales from advertising, the PRODUCT_07 and
cloud services.

EP_0001_E03
The Company has SEGMENT_14 operations with sales outside the U.S. representing a majority of the Company’s total net sales. In
addition, the Company’s global supply chain is large and complex and a majority of the Company’s supplier facilities, including
manufacturing and assembly sites, are located outside the U.S. As a result, the Company’s operations and performance depend
significantly on global and regional economic conditions.
Adverse macroeconomic conditions, including slow growth or recession, high unemployment, inflation, tighter credit, higher interest
rates, and currency fluctuations, can adversely impact consumer confidence and spending and materially adversely affect demand
for the Company’s products and services. In addition, consumer confidence and spending can be materially adversely affected in
response to changes in fiscal and monetary policy, financial market volatility, declines in income or asset values, and other economic
factors.
Uncertainty about, or a decline in, global or regional economic conditions can also have a significant impact on the Company’s
suppliers, contract manufacturers, logistics providers, distributors, cellular network carriers and other channel partners, and
developers. Potential outcomes include financial instability; inability to obtain credit to finance business operations; and insolvency.

Facts:
[{'evidence_id': 'EP_0001_E01',
  'fact_id': 'EP_0001_F01',
  'metric': 'net_sales',
  'period': {'end': '2025-09-27', 'label': 'FY2025', 'start': '2024-09-29'},
  'unit': 'USD_million',
  'value': '416161'},
 {'evidence_id': 'EP_0001_E01',
  'fact_id': 'EP_0001_F02',
  'metric': 'net_sales',
  'period': {'end': '2024-09-28', 'label': 'FY2024', 'start': '2023-10-01'},
  'unit': 'USD_million',
  'value': '391035'},
 {'evidence_id': 'EP_0001_E01',
  'fact_id': 'EP_0001_F03',
  'metric': 'services_net_sales',
  'period': {'end': '2025-09-27', 'label': 'FY2025', 'start': '2024-09-29'},
  'unit': 'USD_million',
  'value': '109158'},
 {'evidence_id': 'EP_0001_E01',
  'fact_id': 'EP_0001_F04',
  'metric': 'services_net_sales',
  'period': {'end': '2024-09-28', 'label': 'FY2024', 'start': '2023-10-01'},
  'unit': 'USD_million',
  'value': '96169'},
 {'evidence_id': 'EP_0001_E01',
  'fact_id': 'EP_0001_F05',
  'metric': 'wearables_home_accessories_net_sales',
  'period': {'end': '2025-09-27', 'label': 'FY2025', 'start': '2024-09-29'},
  'unit': 'USD_million',
  'value': '35686'},
 {'evidence_id': 'EP_0001_E01',
  'fact_id': 'EP_0001_F06',
  'metric': 'wearables_home_accessories_net_sales',
  'period': {'end': '2024-09-28', 'label': 'FY2024', 'start': '2023-10-01'},
  'unit': 'USD_million',
  'value': '37005'}]

In [6]:
for name in ['answer_key', 'initial_report', 'review', 'final_report', 'trader']:
    print('\n' + name)
    pprint(data[name])
print('\nReview note:', item['note'])
display(comparison.loc[comparison['sample_index'] == sample_index,
                       ['field', 'applicable', 'original', 'targeted', 'reviewed']])

answer_key
{'correction_criterion': 'Restore the expected statement or retract the '
                         'injected assertion: EP_0001_E02 supports: Services '
                         'net sales increased during 2025 compared to 2024 '
                         'primarily due to higher net sales from advertising, '
                         'the PRODUCT_07 and cloud services.',
 'defect_type': 'citation_misattribution',
 'detection_criterion': 'Identify the single citation_misattribution defect: '
                        'EP_0001_E03 reports: “Services net sales increased '
                        'during 2025 compared to 2024 primarily due to higher '
                        'net sales from advertising, the PRODUCT_07 and cloud '
                        'services.”',
 'evidence_ids': ['EP_0001_E02'],
 'expected': {'claim_id': 'C4',
              'correct_citation': 'EP_0001_E02',
              'details': 'The quoted financial statement is supported by '
                         'EP_0001_E02; EP_0001_E03 exists but discusses risk '
                         'and does not support it. Restore only the source '
                         'attribution.',
              'evidence_ids': ['EP_0001_E02'],
              'incorrect_citation': 'EP_0001_E03',
              'source_quotes': [{'evidence_id': 'EP_0001_E02',
                                 'quote': 'Services net sales increased during '
                                          '2025 compared to 2024 primarily due '
                                          'to higher net sales from '
                                          'advertising, the PRODUCT_07 and '
                                          'cloud services.'}],
              'statement': 'EP_0001_E02 supports: Services net sales increased '
                           'during 2025 compared to 2024 primarily due to '
                           'higher net sales from advertising, the PRODUCT_07 '
                           'and cloud services.'},
 'explanation': 'The quoted financial statement is supported by EP_0001_E02; '
                'EP_0001_E03 exists but discusses risk and does not support '
                'it. Restore only the source attribution.',
 'injected': {'statement': 'EP_0001_E03 reports: “Services net sales increased '
                           'during 2025 compared to 2024 primarily due to '
                           'higher net sales from advertising, the PRODUCT_07 '
                           'and cloud services.”'},
 'materiality_criterion': 'The unresolved defect is relied on to support an '
                          'accepted recommendation.',
 'target_claim_id': 'C4'}

initial_report
{'claims': [{'check_spec': {'from_fact_id': 'EP_0001_F02',
                            'from_period': {'end': '2024-09-28',
                                            'label': 'FY2024',
                                            'start': '2023-10-01'},
                            'kind': 'percentage_change',
                            'metric': 'net_sales',
                            'to_fact_id': 'EP_0001_F01',
                            'to_period': {'end': '2025-09-27',
                                          'label': 'FY2025',
                                          'start': '2024-09-29'},
                            'unit': 'percent',
                            'value': '6.43'},
             'claim_id': 'C1',
             'evidence_ids': ['EP_0001_E01'],
             'text': 'Total net sales for COMPANY_01 increased by 6.43% from '
                     '$391,035 million in fiscal year 2024 to $416,161 million '
                     'in fiscal year 2025 (Item 7, EP_0001_E01).'},
            {'check_spec': {'from_fact_id': 'EP_0001_F04',
                            'from_period': {'end': '2024-09-28',
                                            'label': 'FY2024',
                                            'start': '2023-10-01'},
                            'kind': 'percentage_change',
                            'metric': 'services_net_sales',
                            'to_fact_id': 'EP_0001_F03',
                            'to_period': {'end': '2025-09-27',
                                          'label': 'FY2025',
                                          'start': '2024-09-29'},
                            'unit': 'percent',
                            'value': '13.51'},
             'claim_id': 'C2',
             'evidence_ids': ['EP_0001_E01', 'EP_0001_E02'],
             'text': 'The Services sales category experienced a 13.51% '
                     'increase in net sales, rising from $96,169 million in '
                     'fiscal year 2024 to $109,158 million in fiscal year 2025 '
                     '(Item 7, EP_0001_E01). This growth was primarily driven '
                     'by higher net sales from advertising, PRODUCT_07, and '
                     'cloud services (Item 7, EP_0001_E02).'},
            {'check_spec': {'from_fact_id': 'EP_0001_F06',
                            'from_period': {'end': '2024-09-28',
                                            'label': 'FY2024',
                                            'start': '2023-10-01'},
                            'kind': 'percentage_change',
                            'metric': 'wearables_home_accessories_net_sales',
                            'to_fact_id': 'EP_0001_F05',
                            'to_period': {'end': '2025-09-27',
                                          'label': 'FY2025',
                                          'start': '2024-09-29'},
                            'unit': 'percent',
                            'value': '-3.56'},
             'claim_id': 'C3',
             'evidence_ids': ['EP_0001_E01', 'EP_0001_E02'],
             'text': 'Conversely, the Wearables, Home and Accessories sales '
                     'category saw a decrease in net sales of 3.56%, from '
                     '$37,005 million in fiscal year 2024 to $35,686 million '
                     'in fiscal year 2025 (Item 7, EP_0001_E01). This decline '
                     'was primarily due to lower net sales of Accessories and '
                     'Wearables (Item 7, EP_0001_E02).'},
            {'check_spec': None,
             'claim_id': 'C4',
             'evidence_ids': ['EP_0001_E03'],
             'text': "COMPANY_01's operations and performance are "
                     'significantly dependent on global and regional economic '
                     'conditions, as sales outside the U.S. represent a '
                     'majority of total net sales and most supplier facilities '
                     'are located outside the U.S. (Item 1A, EP_0001_E03). '
                     'Adverse macroeconomic conditions, such as slow growth, '
                     'inflation, or higher interest rates, can negatively '
                     "impact consumer confidence and demand for the company's "
                     'products and services (Item 1A, EP_0001_E03). '
                     'EP_0001_E03 reports: “Services net sales increased '
                     'during 2025 compared to 2024 primarily due to higher net '
                     'sales from advertising, the PRODUCT_07 and cloud '
                     'services.”'}],
 'rationale': 'COMPANY_01 demonstrated overall net sales growth in fiscal year '
              '2025, driven by strong performance in its Services sales '
              'category. However, the decline in the Wearables, Home and '
              'Accessories sales category indicates some areas of weakness. '
              "Furthermore, the company's significant exposure to global "
              'economic conditions presents a material risk. Given the mixed '
              'performance across sales categories and the identified '
              'macroeconomic risks, a HOLD recommendation is appropriate at '
              'this time.',
 'recommendation': 'HOLD'}

review
[{'calibration_concern': 'Three of four quantitative claims (C1, C2, C3) '
                         'report calculated percentages to two decimal places '
                         "that differ from the filing's own rounded "
                         'whole-percentage disclosures. This is not a factual '
                         'error but a presentation risk: readers may interpret '
                         "the extra precision as the company's reported "
                         'figure. The misattribution in C4 is a clear citation '
                         'error.',
  'challenges': [{'challenge_id': 'RM_R1_01',
                  'defect_type': 'arithmetic',
                  'evidence_ids': ['EP_0001_E01'],
                  'explanation': 'The claim states total net sales increased '
                                 'by 6.43%. Using the cited facts (FY2024: '
                                 '$391,035M; FY2025: $416,161M), the precise '
                                 'percentage change is (416161 - 391035) / '
                                 '391035 * 100 = 6.4255...%, which rounds to '
                                 '6.43% (two decimals). However, the source '
                                 'filing (Item 7, EP_0001_E01) explicitly '
                                 "reports the change as '6 %' (a whole "
                                 'percentage). The claim presents a calculated '
                                 'figure with two-decimal precision that '
                                 "differs from the filing's rounded "
                                 'disclosure. While not a factual error, it '
                                 'creates a precision mismatch with the '
                                 'primary source.',
                  'requested_change': "Either quote the filing's rounded '6%' "
                                      'figure directly (labeling it as the '
                                      "filing's rounded disclosure) or retain "
                                      'the calculated 6.43% with a note that '
                                      'it is a precise calculation from the '
                                      "raw figures, not the filing's reported "
                                      'percentage.',
                  'target_claim_id': 'C1'},
                 {'challenge_id': 'RM_R1_02',
                  'defect_type': 'arithmetic',
                  'evidence_ids': ['EP_0001_E01'],
                  'explanation': 'The claim states Services net sales '
                                 'increased by 13.51%. Using the cited facts '
                                 '(FY2024: $96,169M; FY2025: $109,158M), the '
                                 'precise percentage change is (109158 - '
                                 '96169) / 96169 * 100 = 13.5064...%, which '
                                 'rounds to 13.51% (two decimals). The source '
                                 'filing (Item 7, EP_0001_E01) reports the '
                                 "change as '13 %' (a whole percentage). The "
                                 'claim presents a calculated figure with '
                                 'two-decimal precision that differs from the '
                                 "filing's rounded disclosure.",
                  'requested_change': "Either quote the filing's rounded '13%' "
                                      'figure directly (labeling it as the '
                                      "filing's rounded disclosure) or retain "
                                      'the calculated 13.51% with a note that '
                                      'it is a precise calculation from the '
                                      "raw figures, not the filing's reported "
                                      'percentage.',
                  'target_claim_id': 'C2'},
                 {'challenge_id': 'RM_R1_03',
                  'defect_type': 'arithmetic',
                  'evidence_ids': ['EP_0001_E01'],
                  'explanation': 'The claim states Wearables, Home and '
                                 'Accessories net sales decreased by 3.56%. '
                                 'Using the cited facts (FY2024: $37,005M; '
                                 'FY2025: $35,686M), the precise percentage '
                                 'change is (35686 - 37005) / 37005 * 100 = '
                                 '-3.5643...%, which rounds to -3.56% (two '
                                 'decimals). The source filing (Item 7, '
                                 "EP_0001_E01) reports the change as '(4)%' (a "
                                 'whole percentage). The claim presents a '
                                 'calculated figure with two-decimal precision '
                                 "that differs from the filing's rounded "
                                 'disclosure.',
                  'requested_change': "Either quote the filing's rounded "
                                      "'(4)%' figure directly (labeling it as "
                                      "the filing's rounded disclosure) or "
                                      'retain the calculated -3.56% with a '
                                      'note that it is a precise calculation '
                                      "from the raw figures, not the filing's "
                                      'reported percentage.',
                  'target_claim_id': 'C3'},
                 {'challenge_id': 'RM_R1_04',
                  'defect_type': 'citation_misattribution',
                  'evidence_ids': ['EP_0001_E03'],
                  'explanation': 'Claim C4 ends with a direct quotation '
                                 "attributed to EP_0001_E03: 'Services net "
                                 'sales increased during 2025 compared to 2024 '
                                 'primarily due to higher net sales from '
                                 'advertising, the PRODUCT_07 and cloud '
                                 "services.' This sentence does not appear in "
                                 'EP_0001_E03 (Item 1A risk factors). It '
                                 'appears in EP_0001_E02 (Item 7 segment '
                                 'commentary). The quotation is misattributed '
                                 'to the wrong evidence item.',
                  'requested_change': 'Remove the misattributed quotation from '
                                      'Claim C4, or correct the citation to '
                                      'reference EP_0001_E02 (Item 7) instead '
                                      'of EP_0001_E03 (Item 1A).',
                  'target_claim_id': 'C4'}],
  'overall_assessment': "The analyst's directional conclusions are correct and "
                        'supported by the evidence. However, the report '
                        'contains precision mismatches versus the source '
                        'filing on all three percentage-change claims and a '
                        'citation misattribution in the risk-factor claim. '
                        'These should be corrected before the report is '
                        'finalized.'}]

final_report
{'claims': [{'check_spec': {'from_fact_id': 'EP_0001_F02',
                            'from_period': {'end': '2024-09-28',
                                            'label': 'FY2024',
                                            'start': '2023-10-01'},
                            'kind': 'percentage_change',
                            'metric': 'net_sales',
                            'to_fact_id': 'EP_0001_F01',
                            'to_period': {'end': '2025-09-27',
                                          'label': 'FY2025',
                                          'start': '2024-09-29'},
                            'unit': 'percent',
                            'value': '6.43'},
             'claim_id': 'C1',
             'evidence_ids': ['EP_0001_E01'],
             'text': 'Total net sales for COMPANY_01 increased by 6.43% from '
                     '$391,035 million in fiscal year 2024 to $416,161 million '
                     'in fiscal year 2025 (Item 7, EP_0001_E01). The filing '
                     'reports this change as 6% (rounded).'},
            {'check_spec': {'from_fact_id': 'EP_0001_F04',
                            'from_period': {'end': '2024-09-28',
                                            'label': 'FY2024',
                                            'start': '2023-10-01'},
                            'kind': 'percentage_change',
                            'metric': 'services_net_sales',
                            'to_fact_id': 'EP_0001_F03',
                            'to_period': {'end': '2025-09-27',
                                          'label': 'FY2025',
                                          'start': '2024-09-29'},
                            'unit': 'percent',
                            'value': '13.51'},
             'claim_id': 'C2',
             'evidence_ids': ['EP_0001_E01', 'EP_0001_E02'],
             'text': 'The Services sales category experienced a 13.51% '
                     'increase in net sales, rising from $96,169 million in '
                     'fiscal year 2024 to $109,158 million in fiscal year 2025 '
                     '(Item 7, EP_0001_E01). The filing reports this change as '
                     '13% (rounded). This growth was primarily driven by '
                     'higher net sales from advertising, PRODUCT_07, and cloud '
                     'services (Item 7, EP_0001_E02).'},
            {'check_spec': {'from_fact_id': 'EP_0001_F06',
                            'from_period': {'end': '2024-09-28',
                                            'label': 'FY2024',
                                            'start': '2023-10-01'},
                            'kind': 'percentage_change',
                            'metric': 'wearables_home_accessories_net_sales',
                            'to_fact_id': 'EP_0001_F05',
                            'to_period': {'end': '2025-09-27',
                                          'label': 'FY2025',
                                          'start': '2024-09-29'},
                            'unit': 'percent',
                            'value': '-3.56'},
             'claim_id': 'C3',
             'evidence_ids': ['EP_0001_E01', 'EP_0001_E02'],
             'text': 'Conversely, the Wearables, Home and Accessories sales '
                     'category saw a decrease in net sales of 3.56%, from '
                     '$37,005 million in fiscal year 2024 to $35,686 million '
                     'in fiscal year 2025 (Item 7, EP_0001_E01). The filing '
                     'reports this change as (4)% (rounded). This decline was '
                     'primarily due to lower net sales of Accessories and '
                     'Wearables (Item 7, EP_0001_E02).'},
            {'check_spec': None,
             'claim_id': 'C4',
             'evidence_ids': ['EP_0001_E03'],
             'text': "COMPANY_01's operations and performance are "
                     'significantly dependent on global and regional economic '
                     'conditions, as sales outside the U.S. represent a '
                     'majority of total net sales and most supplier facilities '
                     'are located outside the U.S. (Item 1A, EP_0001_E03). '
                     'Adverse macroeconomic conditions, such as slow growth, '
                     'inflation, or higher interest rates, can negatively '
                     "impact consumer confidence and demand for the company's "
                     'products and services (Item 1A, EP_0001_E03).'}],
 'rationale': 'COMPANY_01 demonstrated overall net sales growth in fiscal year '
              '2025, driven by strong performance in its Services sales '

                         field  applicable original targeted reviewed
290   answer_key_matches_input        True     True     True     True
291      risk_manager_detected        True     True     True     True
292            defect_resolved        True     True     True     True
293  materially_used_by_trader        True    False    False    False
294          new_error_present        True    False    False     True

## What were the earlier 34 checks?

29 flagged outputs + 3 uncertain outputs + 2 worked examples.

31 checked Trader reliance only. Three checked all five fields: 46 field decisions altogether, including non-applicable fields. Only eight of those outputs overlap this 118-record sample. These were targeted checks, not a random validation sample.

Every earlier check is listed below. `review_index` also selects it in [review_flagged_cases.ipynb](review_flagged_cases.ipynb).

In [7]:
inventory = pd.DataFrame(read('targeted_34_inventory.json'))
display(inventory[['review_index', 'packet_id', 'batch', 'architecture', 'defect_type', 'fields_checked']])
print('Full notes: output/sample_review_20261024/targeted_34_inventory.csv')
print('All 118 notes: output/sample_review_20261024/reviews.csv')

,review_index,packet_id,batch,architecture,defect_type,fields_checked
0,0,EP_0002,confidence_repeat,baseline,arithmetic,5
1,1,EP_0007,main_study,hybrid,clean,5
2,2,EP_0008,main_study,debate,clean,5
3,3,EP_0002,main_study,baseline,material_omission,1
4,4,EP_0010,main_study,debate,material_omission,1
5,5,EP_0004,main_study,verification,material_omission,1
6,6,EP_0001,main_study,debate,material_omission,1
7,7,EP_0001,main_study,verification,material_omission,1
8,8,EP_0002,main_study,verification,material_omission,1
9,9,EP_0002,main_study,hybrid,material_omission,1
10,10,EP_0003,main_study,baseline,material_omission,1
11,11,EP_0004,main_study,debate,material_omission,1
12,12,EP_0004,main_study,hybrid,material_omission,1
13,13,EP_0005,main_study,baseline,material_omission,1
14,14,EP_0006,main_study,baseline,material_omission,1
15,15,EP_0006,main_study,debate,material_omission,1
16,16,EP_0006,main_study,verification,material_omission,1
17,17,EP_0006,main_study,hybrid,material_omission,1
18,18,EP_0007,main_study,debate,material_omission,1
19,19,EP_0010,main_study,baseline,material_omission,1
20,20,EP_0010,main_study,verification,material_omission,1
21,21,EP_0010,main_study,hybrid,material_omission,1
22,22,EP_0012,main_study,baseline,material_omission,1
23,23,EP_0012,main_study,verification,material_omission,1
24,24,EP_0012,main_study,hybrid,material_omission,1
25,25,EP_0013,main_study,debate,material_omission,1
26,26,EP_0013,main_study,verification,material_omission,1
27,27,EP_0014,main_study,baseline,material_omission,1
28,28,EP_0014,main_study,verification,material_omission,1
29,29,EP_0014,main_study,hybrid,material_omission,1
30,30,EP_0003,main_study,verification,material_omission,1
31,31,EP_0004,main_study,baseline,material_omission,1
32,32,EP_0005,confidence_study,baseline,material_omission,1
33,33,EP_0005,confidence_repeat,baseline,material_omission,1

Full notes: output/sample_review_20261024/targeted_34_inventory.csv
All 118 notes: output/sample_review_20261024/reviews.csv

## Other issues and next step

A numerical check can fail even when the prose is faithful to the filing. These issues are recorded separately from new factual errors.

The follow-up consistency checks and separate final export are complete. See [explore_results.ipynb](explore_results.ipynb) for updated study-wide metrics. The sample counts here remain the historical sample review; they are not extrapolated to all runs. The independent human-review notebook remains available if an independent agreement estimate is needed.

In [8]:
findings = read('review_findings.json')
for item in findings['separate_issues']:
    print('\nSample', item['sample_index'])
    print(item['issue'])
print('\nStructured claims checked:', summary['structured_claim_checks'])
print('Original runs and scores preserved; this notebook only reads saved files.')

Sample 36
The arithmetic key describes 15.1% prose, but the saved report says 115.1%. Both are wrong for the same metric and period, so the key remains usable under the rubric; the severity differs from the description.

Sample 64
A semantically correct metric rename from cloud_gross_margin_percentage to PRODUCT_10_gross_margin_percentage causes exact-name verification to fail. The 69% value, period and cited fact remain correct. This is a structured-contract mismatch, not a new financial falsehood.

Sample 94
The final report faithfully quotes filing-rounded 4%, -15% and -24%, but copies them into calculated percentage-change fields. These fail the 0.01-point tolerance against 4.29%, -14.70% and -24.17%, and the Trader rejects the report. Separate faithful prose quotation from precise structured arithmetic.

Structured claims checked: 1044
Original runs and scores preserved; this notebook only reads saved files.